export const ACTION_STATES={
ADD_EMAIL:"ADD_EMAIL",
ADD_FIRSTNAME:"ADD_FIRSTNAME",
ADD_LASTNAME:"ADD_LASTNAME",
ADD_DATE:"ADD_DATE",
ADD_TITLE:"ADD_TITLE",
ADD_PASSWORD:"ADD_PASSWORD",
SIGN_UP:"SIGN_UP",
SIGN_IN:"SIGN_IN"
}